;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="InputTag.Shift",NewTagName="InputTag.Run")
+GameplayTagRedirects=(OldTagName="Frette.Inventory.SlotTag.Chest",NewTagName="Frette.Inventory.SlotType.Chest")
+GameplayTagRedirects=(OldTagName="Frette.Inventory.SlotTag",NewTagName="Frette.Inventory.SlotType")
+GameplayTagRedirects=(OldTagName="Frette.Inventory.SlotType.Chest",NewTagName="Frette.Inventory.SlotType.Torso")
+GameplayTagList=(Tag="BodyPartValues.ThermalImpedance",DevComment="")
+GameplayTagList=(Tag="Cooldown.BoostMaxHealth",DevComment="")
+GameplayTagList=(Tag="Frette.Abiilty.Mantling",DevComment="")
+GameplayTagList=(Tag="Frette.BodyPartValues.ThermalImpedance",DevComment="")
+GameplayTagList=(Tag="Frette.Inventory.SlotType.Foot",DevComment="")
+GameplayTagList=(Tag="Frette.Inventory.SlotType.Hand",DevComment="")
+GameplayTagList=(Tag="Frette.Inventory.SlotType.Head",DevComment="")
+GameplayTagList=(Tag="Frette.Inventory.SlotType.Legs",DevComment="")
+GameplayTagList=(Tag="Frette.Inventory.SlotType.Torso",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability1",DevComment="")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.Run",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.Primary",DevComment="Primary action of the weapon")
+GameplayTagList=(Tag="InputTag.Weapon.Reload",DevComment="")
+GameplayTagList=(Tag="InputTag.Weapon.Secondary",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.HandsHurt",DevComment="")
+GameplayTagList=(Tag="State.immobilized",DevComment="")
+GameplayTagList=(Tag="State.Sprinting",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Aiming",DevComment="")
+GameplayTagList=(Tag="ThermalImpedance",DevComment="")

